Repository Point72/csp-gateway, pull requests merged in 2025-03, with the labels that each got.

#29 Bump perspective dependency, avoid bad version, drop unused js dependencies
  js/package.json
  js/pnpm-lock.yaml
  pyproject.toml
Labels: part: dependencies

#30 Fix broken link in docs
  docs/wiki/Overview.md
Labels: part: documentation

#33 Add coercion to str from num
  csp_gateway/tests/utils/struct/test_base.py
  csp_gateway/utils/struct/base.py
Labels: type: enhancement

#39 Move regular-table to light dom, style td with user select for convenience
  js/src/index.jsx
  js/src/style/perspective.css
Labels: lang: javascript

#42 Fix to RWKafka to pulling engine times from Kafka message
  csp_gateway/server/modules/kafka/kafka.py
  csp_gateway/tests/server/modules/kafka/test_kafka.py
Labels: lang: python, type: bug

#40 Make client a ccflow basemodel, allow config to be configureable from e.g. hydra
  .gitignore
  csp_gateway/client/client.py
Labels: type: enhancement

#44 remove unnecessary placeholder in opsgenie logging
  csp_gateway/server/modules/logging/opsgenie.py
Labels: tag: internal
